

<!--
	Author: W3layouts
	Author URL: http://w3layouts.com
	License: Creative Commons Attribution 3.0 Unported
	License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html lang="en">
<!-- Head -->
<head>
<title>ENCOM 2018 - Conferência Nacional em Comunicações, Redes e Segurança da Informação</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<meta name="keywords" content="Encom 2018 é uma conferência científica, acadêmica, profissional." />

<!-- gallery -->
<link rel="stylesheet" href="css/lightGallery.css" type="text/css" media="all" />
<link rel="stylesheet" type="text/css" href="css/component.css" />

<!-- //gallery -->
<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />
<script src="js/modernizr.custom.js"></script>
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
<link href="css/font-awesome.min.css" rel="stylesheet" type="text/css" media="all" />
<link href="//fonts.googleapis.com/css?family=Arimo:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,hebrew,latin-ext,vietnamese" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Covered+By+Your+Grace" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Merriweather+Sans" rel="stylesheet">
<link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico"/>


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-108825846-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-108825846-1');
</script>


<!--Start-slider-script-->
<script type="text/javascript">		
	$(window).load(function(){
	$('.flexslider').flexslider({
		animation: "slide",
		start: function(slider){
			$('body').removeClass('loading');
		}
	});
	});
</script>

<!--End-slider-script-->
</head>
<!-- Head -->
<body>
<!-- Slider -->
<div class="w3-banner-info-agile">
		<div class="slider w3layouts agileits">
			<ul class="rslides w3layouts agileits" id="slider">
				<li>
						<div class="layer w3layouts agileits-banner">
							<h3>VIII Conferência Nacional em Comunicações, Redes e Segurança da Informação</h3>
							<p>Universidade Federal da Bahia - UFBA / 19, 20 e 21 de Outubro de 2018.</p>
							<!-- <a href="#">read more</a> -->
						</div>
				</li>
				<li>
						<div class="layer w3layouts agileits-banner agileits-banner1">
							<h3>VIII Conferência Nacional em Comunicações, Redes e Segurança da Informação</h3>
							<p>Universidade Federal da Bahia - UFBA / 19, 20 e 21 de Outubro de 2018.</p>
							<!-- <a href="#">read more</a> -->
						</div>
				</li>
				<li>
						<div class="layer w3layouts agileits-banner agileits-banner2">
							<h3>VIII Conferência Nacional em Comunicações, Redes e Segurança da Informação</h3>
							<p>Universidade Federal da Bahia - UFBA / 19, 20 e 21 de Outubro de 2018.</p>
							<!-- <a href="#">read more</a> -->
						</div>
				</li>
			</ul>
		</div>
</div>
<!-- //Slider -->
<!-- banner -->
<div class="banner" id="home">

		<!-- <div class="container"> -->
			<nav class="navbar navbar-default cl-effect-5"  id="cl-effect-5">
				<div class="navbar-header navbar-left">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<h1><a class="navbar-brand" href="index.html">Encom 2018</a></h1>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
          				<li><a href="#"><span data-hover="Início">Início</span></a></li>
						<li><a class="active scroll" href="#models"><span data-hover="O Evento">O Evento</span></a></li> 
						<li><a class="scroll" href="#services"><span data-hover="Organização">Organização</span></a></li>
						<li><a class="scroll" href="#gallery"><span data-hover="Local_do_Evento">Local do Evento</span></a></li>
						<li><a class="scroll" href="#instrucoes"><span data-hover="Instruções">Instruções</span></a></li>
						<li><a class="scroll" href="#submissoes"><span data-hover="Submissões">Submissoes</span></a></li>
						<li><a class="scroll" href="#datas"><span data-hover="Datas">Datas</span></a></li>
						<li><a class="scroll" href="#contact"><span data-hover="Contato">Contato</span></a></li>
         			</ul>
       			</div>
        		<!-- /.navbar-collapse -->
			</nav>	   
		<!-- </div> -->

</div>
<!-- //banner -->	

		<div id="google-translator" style="margin-left: 20px; margin-top: 10px;">

			<div id="google_translate_element"></div><script type="text/javascript">
							function googleTranslateElementInit() {
							  new google.translate.TranslateElement({pageLanguage: 'pt', includedLanguages: 'en,es', layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL}, 'google_translate_element');
							}
							</script>	
			</div>
		</div>

	<!-- special models -->
		<div class="agileits-w3layouts-specials" id="models">
			<h3>Encom &amp Iecom</h3>
			<span></span>
				<div class="special-grids">
					<div class="col-md-6 special-left l-grids">
						 <figure class="effect-bubba">
								<img src="images/s222.jpg" alt=""/>
								<figcaption>
									<h4>Iecom</h4>
									<p>Foto em perspectiva da sede do Instituto de Estudos Avançados em Comunicações, localizada na Universidade Federal de Campina Grande.</p>													
								</figcaption>			
						 </figure>
					</div>
					<div class="col-md-6 special-right">
						<div class="sp-wid">
							<h4>O Iecom</h4>
							<p style="color: white">O Instituto de Estudos Avançados em Comunicações, também designado pela sigla Iecom, constituído em 1 de julho de 2003, é uma pessoa jurídica de direito privado, sem fins lucrativos, e duração por tempo indeterminado, com sede no município de Campina Grande, Estado da Paraíba, em que é de Utilidade Pública de acordo com a Lei Municipal 4.650.</p> 

							<p style="color: white; padding-bottom: 30px">O Iecom tem como missão a promoção à cultura, incentivo ao voluntariado e a inserção de estudantes no mercado de trabalho, desenvolvimento tecnológico, formação técnico-científica, fomento à produção científica de alto nível e intercâmbio entre comunidades científicas de interesses afins. Para conhecer mais sobre o Iecom, visite a página http://iecom.org.br.</p>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="where-spl">
					<div class="col-md-6 special-right l-left">
						<div class="l-wid">
							<h4>O encontro: ENCOM</h4>
							<p style="color: white">O Encontro Anual do Iecom em Comunicação, Redes e Criptografia, ENCOM, em sua 8º edição, passa a se chamar Conferência Nacional em Comunicação, Redes e Segurança da Informação. O Encom é realizado anualmente pelo Instituto de Estudos Avançados em Comunicações, Iecom, em parceria com Instituições de Ensino Superior, agências de fomento no âmbito científico, como também patrocínio de empresas renomadas no segmento da Tecnologia da Informação e Comunicação.</p> 

							<p style="color: white">No decorrer de suas edições, o ENCOM tem reunido pesquisadores, estudantes, professores, empresários e profissionais das áreas de comunicações, telemática, redes de computadores, informática, segurança de redes, criptografia e do mercado de telecomunicações, para apresentação de resultados de pesquisas e soluções nessas áreas e em temas correlatos.</p>

							<p style="color: white; padding-bottom: 30px">O ENCOM 2018 será realizado, nos dias 19, 20 e 21 de outubro de 2018, na Universidade Federal do Maranhão (UFBA), com o apoio da Universidade Federal de Campina Grande (UFCG), da Universidade Federal da Paraíba (UFPB), do Instituto Federal de Educação, Ciência e Tecnologia (IFPB), da Rohde&Schwartz, e contará com a presença de renomados palestrantes nacionais e internacionais.</p>
						</div>
						
					</div>
					<div class="col-md-6 special-left l-right l-grids">
						 <figure class="effect-bubba">
								<img src="images/s111.jpg" alt=""/>
								<figcaption>
									<h4>Encom</h4>
									<p>O Encom já foi realizado em diversas cidades do nordeste brasileiro, como exemplo: Campina Grande (PB), João Pessoa (PB), Recife (PE), Fortaleza (CE) e São Luís (MA). A edição de número 8 será realizada em Salvador (BA).</p>																
								</figcaption>			
						 </figure>
					</div>
					<div class="clearfix"></div>
				</div>
		</div>
		<!-- special models-->

<!--services-->
	<div id="services" class="services">
		<!-- container -->
		<div class="container">
			<h3 class="title wow zoomInLeft animated" data-wow-delay=".5s">ORGANIZAÇÃO</h3>
			<span></span>
			<div class="services-row">
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/malencar.jpeg"></span>
					<div class="services-text">
						<h4>Marcelo Sampaio de Alencar</h4>
						<p>Coordenador Geral do Encom 2018 (Iecom, UFCG)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/vitaly.jpg"></span>
					<div class="services-text">
						<h4>Vitaly Esquerre</h4>
						<p>Coordenador Geral do Encom 2018 (UFBA) </p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/valdemar.jpg"></span>
					<div class="services-text">
						<h4>Valdemar Cardoso da Rocha Jr.</h4>
						<p>Editoria de Publicações (Iecom, UFPE)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/profile.jpg"></span>
					<div class="services-text">
						<h4>Wamberto José Lira de Queiroz</h4>
						<p>Editoria de Publicações (Iecom, UFCG)</p>
					</div>
				</div>

				<div class="clearfix"> </div>
			</div>

			<div class="services-row">
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/fabricio2.jpg"></span>
					<div class="services-text">
						<h4>Fabrício Braga Soares de Carvalho</h4>
						<p>Coordenação de Divulgação (Iecom, UFPB)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/felipe.jpg"></span>
					<div class="services-text">
						<h4>Felipe Pinheiro Correia</h4>
						<p>Coordenação de Divulgação (IFSertão-PE)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/jose_sampaio.jpg"></span>
					<div class="services-text">
						<h4>José Sampaio de Lemos Neto</h4>
						<p>Coordenação de Divulgação (UFPE)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/profile.jpg"></span>
					<div class="services-text">
						<h4>Maria de Lourdes M. Guedes Alcoforado</h4>
						<p>Coordenação de Divulgação (Iecom, UPE)</p>
					</div>
				</div>

				<div class="clearfix"> </div>
			</div>

			<div class="services-row">
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/alex.jpg"></span>
					<div class="services-text">
						<h4>Alex Ferreira dos Santos</h4>
						<p>Coordenador Local do Evento (UFRB)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/eduardo.jpg"></span>
					<div class="services-text">
						<h4>Eduardo Furtado de Simas Filho</h4>
						<p>Coordenador Local do Evento (UFBA)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/profile.jpg"></span>
					<div class="services-text">
						<h4>Hélio Moreira de Mesquita</h4>
						<p>Coordenador Local do Evento (Iecom)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/gustavo.jpg"></span>
					<div class="services-text">
						<h4>Gustavo Nóbrega Martins</h4>
						<p>Coordenação de Informática e Inscrições (Iecom, IFPE)</p>
					</div>
				</div>

				<div class="clearfix"> </div>
			</div>

			<div class="services-row">
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/raissa.jpg"></span>
					<div class="services-text">
						<h4>Raíssa Bezerra Rocha</h4>
						<p>Coordenação de Informática e Inscrições (Iecom, UFS)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/ruan.jpg"></span>
					<div class="services-text">
						<h4>Ruan Delgado Gomes</h4>
						<p>Coordenação de Informática e Inscrições (Iecom, IFPB)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/fabricio_geronimo.jpg"></span>
					<div class="services-text">
						<h4>Fabrício Gerônimo Simões Silva</h4>
						<p>Coordenação de Captação de Recursos (IFBA)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/jose.jpg"></span>
					<div class="services-text">
						<h4>Joberto Sérgio Barbosa Martins</h4>
						<p>Coordenação de Captação de Recursos (Unifacs)</p>
					</div>
				</div>

				<div class="clearfix"> </div>
			</div>

			<div class="services-row">
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/paulo.jpg"></span>
					<div class="services-text">
						<h4>Paulo Ribeiro Lins Jr.</h4>
						<p>Coordenação de Captação de Recursos (Iecom, IFPB)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/karcius.jpg"></span>
					<div class="services-text">
						<h4>Karcius Day Rosario Assis</h4>
						<p>Coordenação Técnica (UFBA)</p>
					</div>
				</div>
				<div class="col-md-3 services-grid services-grid1">
					<img class="img-circle" src="images/waslon.jpg"></span>
					<div class="services-text">
						<h4>Waslon Terllizie A. Lopes</h4>
						<p>Coordenação Técnica (Iecom, UFPB)</p>
					</div>
				</div>

				<div class="clearfix"> </div>
			</div>



			<div class="clearfix"> </div>
		</div>
		<!--//container-->
	</div>
	<!--//services-->
	<!-- gallery -->
	<div class="gallery team-bottom" id="gallery">
		<div class="container">
			<div class="w3l_head w3l_head1">
			<h3>LOCAL DO EVENTO</h3>
			<span></span>
			</div>
			<div class="w3layouts_gallery_grids">
				<ul class="w3l_gallery_grid" id="lightGallery">
					<li data-title="Encom 2018" data-desc="Vista do portão principal da UFBA" data-src="images/ga1.jpg" data-responsive-src="images/ga1.jpg"> 
						<div class="w3layouts_gallery_grid1 box">
							<a href="#">
								<img src="images/ga1.jpg" alt=" " class="img-responsive" />
								<div class="overbox">
									<h4 class="title overtext">Clique para Ampliar</h4>
									
								</div>
							</a>

						</div>
					</li>
					<li data-title="Encom 2018" data-desc="Área interna do campus da UFBA." data-src="images/ga2.jpg" data-responsive-src="images/ga2.jpg"> 
						<div class="w3layouts_gallery_grid1 box">
							<a href="#">
								<img src="images/ga2.jpg" alt=" " class="img-responsive" />
								<div class="overbox">
									<h4 class="title overtext">Clique para Ampliar</h4>
									
								</div>
							</a>
						</div>
					</li>
					<li data-title="Encom 2018" data-desc="Escola de administração da UFBA." data-src="images/ga3.jpg" data-responsive-src="images/ga3.jpg"> 
						<div class="w3layouts_gallery_grid1 box">
							<a href="#">
								<img src="images/ga3.jpg" alt=" " class="img-responsive" />
								<div class="overbox">
									<h4 class="title overtext">Clique para Ampliar</h4>
									
								</div>
							</a>
						</div>
					</li>
					<li data-title="Encom 2018" data-desc="Pavilhão do curso de medicina da UFBA." data-src="images/ga4.jpg" data-responsive-src="images/ga4.jpg"> 
						<div class="w3layouts_gallery_grid1 box">
							<a href="#">
								<img src="images/ga4.jpg" alt=" " class="img-responsive" />
								<div class="overbox">
									<h4 class="title overtext">Clique para Ampliar</h4>
									
								</div>
							</a>
						</div>
					</li>
					<li data-title="Encom 2018" data-desc="Pavilhão do curso de comunicação da UFBA." data-src="images/gal5.jpg" data-responsive-src="images/gal5.jpg"> 
						<div class="w3layouts_gallery_grid1 box">
							<a href="#">
								<img src="images/gal5.jpg" alt=" " class="img-responsive" />
								<div class="overbox">
									<h4 class="title overtext">Clique para Ampliar</h4>
									
								</div>
							</a>
						</div>
					</li>
					<li data-title="Encom 2018" data-desc="Pavilhão do curso de comunicação da UFBA." data-src="images/gal5.jpg" data-responsive-src="images/ga5.jpg"> 
						<div class="w3layouts_gallery_grid1 box">
							<a href="#">
								<img src="images/gal5.jpg" alt=" " class="img-responsive" />
								<div class="overbox">
									<h4 class="title overtext">Clique para Ampliar</h4>
									
								</div>
							</a>
						</div>
					</li>
					<li data-title="Encom 2018" data-desc="Vista do farol da barra na cidade de Salvador." data-src="images/salvador1.jpg" data-responsive-src="images/salvador1.jpg"> 
						<div class="w3layouts_gallery_grid1 box">
							<a href="#">
								<img src="images/salvador1.jpg" alt=" " class="img-responsive" />
								<div class="overbox">
									<h4 class="title overtext">Clique para Ampliar</h4>
									
								</div>
							</a>
						</div>
					</li>
					<li data-title="Encom 2018" data-desc="Vista litoranea da cidade de Salvador." data-src="images/salvador2.jpg" data-responsive-src="images/salvador2.jpg"> 
						<div class="w3layouts_gallery_grid1 box">
							<a href="#">
								<img src="images/salvador2.jpg" alt=" " class="img-responsive" />
								<div class="overbox">
									<h4 class="title overtext">Clique para Ampliar</h4>
									
								</div>
							</a>
						</div>
					</li>
					<li data-title="Encom 2018" data-desc="Cidade antiga, Salvador." data-src="images/salvador3.jpg" data-responsive-src="images/salvador3.jpg"> 
						<div class="w3layouts_gallery_grid1 box">
							<a href="#">
								<img src="images/salvador3.jpg" alt=" " class="img-responsive" />
								<div class="overbox">
									<h4 class="title overtext">Clique para Ampliar</h4>
									
								</div>
							</a>
						</div>
					</li>
						<li data-title="Encom 2018" data-desc="Elevador Lacerda ao entardecer." data-src="images/salvador4.jpg" data-responsive-src="images/salvador4.jpg"> 
						<div class="w3layouts_gallery_grid1 box">
							<a href="#">
								<img src="images/salvador4.jpg" alt=" " class="img-responsive" />
								<div class="overbox">
									<h4 class="title overtext">Clique para Ampliar</h4>
									
								</div>
							</a>
						</div>
					</li>
					<li data-title="Encom 2018" data-desc="Vista frontal do Mercado Modelo com o Forte de Salvador ao fundo." data-src="images/salvador5.jpg" data-responsive-src="images/salvador5.jpg"> 
						<div class="w3layouts_gallery_grid1 box">
							<a href="#">
								<img src="images/salvador5.jpg" alt=" " class="img-responsive" />
								<div class="overbox">
									<h4 class="title overtext">Clique para Ampliar</h4>
									
								</div>
							</a>
						</div>
					</li>
					<li data-title="Encom 2018" data-desc="Vista do Farol da Barra." data-src="images/salvador6.jpg" data-responsive-src="images/salvador6.jpg"> 
						<div class="w3layouts_gallery_grid1 box">
							<a href="#">
								<img src="images/salvador6.jpg" alt=" " class="img-responsive" />
								<div class="overbox">
									<h4 class="title overtext">Clique para Ampliar</h4>
									
								</div>
							</a>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
	
	<!-- //gallery -->

	<!--/team
	<div class="team" id="team">
			<div class="w3-team-head">
				<h3>Our team</h3>
			</div>
			<div class="w3-agile-team-grids">
				<div class="w3-agile-team-grid1">
					<div class="col-md-4 w3-agile-team-img1">
					<div class="w3-agile-team-img-head">
					
						<h3>Blergonce</h3>
						<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<div class="team-social">
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-linkedin"></i></a>
						<a href="#"><i class="fa fa-pinterest-p"></i></a>
						</div>

					</div>
					</div>
					<div class="col-md-4 w3-agile-team-img1 w3-agile-team-img-1">
						<div class="w3-agile-team-img-head">
						<h3>Samuel Badree</h3>
						<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<div class="team-social">
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-linkedin"></i></a>
						<a href="#"><i class="fa fa-pinterest-p"></i></a>
						</div>
					</div>
					
					</div>
					<div class="col-md-4 w3-agile-team-img1 w3-agile-team-img-2">
						<div class="w3-agile-team-img-head">
						<h3>Shakeera ls</h3>
						<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<div class="team-social">
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-linkedin"></i></a>
						<a href="#"><i class="fa fa-pinterest-p"></i></a>
						</div>
					</div>
					
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="w3-agile-team-grid2">
					<div class="col-md-4 w3-agile-team-img1 w3-agile-team-img-3">
						<div class="w3-agile-team-img-head">
						<h3>sharapova</h3>
						<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<div class="team-social">
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-linkedin"></i></a>
						<a href="#"><i class="fa fa-pinterest-p"></i></a>
						</div>
					</div>
					
					</div>
					<div class="col-md-4 w3-agile-team-img1 w3-agile-team-img-4">
					<div class="w3-agile-team-img-head">
						<h3>Jinghat roy</h3>
						<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<div class="team-social">
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-linkedin"></i></a>
						<a href="#"><i class="fa fa-pinterest-p"></i></a>
						</div>
					</div>
					</div>
					<div class="col-md-4 w3-agile-team-img1 w3-agile-team-img-5">
						<div class="w3-agile-team-img-head">
						<h3>jessica rosey</h3>
						<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<div class="team-social">
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-linkedin"></i></a>
						<a href="#"><i class="fa fa-pinterest-p"></i></a>
						</div>
					</div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="clearfix"></div>
			</div>
	</div>
	//team-->
			<div class="agileits-w3layouts-specials" id="submissoes">
			<h3>SUBMISSÕES</h3>
			<span></span>
				<div class="special-grids">
					<div class="col-md-6 special-right l-left2">
						<div class="l-wid">
							<h4 style="color: white">Submissões de Trabalho no ENCOM 2018</h4>
							<p style="color: white">O processo de submissões de trabalho no ENCOM 2018 será feito por meio da ferramenta de gerenciamento de submissões, Easychair. O processo de revisão de trabalho do ENCOM 2018 tem como potítica de avaliação <i>Double Blind Review Process</i>. Conforme cronograma do evento, o link para submissão será disponibilizado nesta seção.</p>
						</div>
						
					</div>
					<div class="col-md-6 special-left l-right l-grids">
						 <figure class="effect-bubba">
								<img src="images/easy-chair.jpg" alt=""/>
								<figcaption>
									<h4>Easychair</h4>
									<p>Atualmente, o Easychair é provavelmente o sistema de gerenciamento de conferências mais utilizado. (Fonte: Easychair website).</p>																
								</figcaption>			
						 </figure>
					</div>
					<div class="where-spl">
						
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
		<!-- special models-->

		<!-- special models -->
		<div class="agileits-w3layouts-specials" id="instrucoes">
			<h3>Instruções para Autores</h3>
			<span></span>
				<div class="special-grids">
					<div class="col-md-6 special-left l-grids">
						 <figure class="effect-bubba">
								<img src="images/EditorNote.jpg" alt=""/>
								<figcaption>
									<h4>Instruções para Autores</h4>
									<p>Fiquem por dentro de algumas dicas para elaboração e submissão do seu trabalho.</p>													
								</figcaption>			
						 </figure>
					</div>
					<div class="col-md-6 special-right">
						<div class="sp-wid">
							<h4><font color="white"><font color="white">Instruções para Autores</h4>
							<p style="color:white">Os artigos submetidos deverão ser escritos em duas páginas com duas colunas e formatados no estilo do IEEE, em Latex, utilizando os arquivos IEEE.tex, IEEEtran.cls e IEEEtran.bst, ou o arquivo TRANS-JOUR.doc, conforme  disponibilizado nos links:&nbsp;
							<a style="color:white" href="http://iecom.org.br/encom2014/Templetes/IEEEtran.zip" class="links"><b>LaTeX</b></a>&nbsp;&nbsp;
						  	<a style="color:white" href="http://iecom.org.br/encom2014/Templetes/TRANS-JOUR.pdf" class="links"><b>PDF</b></a>&nbsp;&nbsp;
						  	<a style="color:white" href="http://iecom.org.br/encom2014/Templetes/TRANS-JOUR.doc" class="links"><b>.DOC</b></a></p>
							<p style="color:white">Com o objetivo de dar celeridade ao processo de publicaçãdos artigos aceitos, é importante que sejam observadas os seguintes pontos sobre a formatação:</p>
							<p style="margin-bottom: 40px">
								<ul style="margin-left: 20px">
									<li style="padding-bottom: 10px;">O idioma oficial do evento é o Português (Brasil), entretanto os idiomas Inglês e Espanhol também são aceitos para escrita e submissão de trabalhos.</li>
									<li style="padding-bottom: 10px;">Os tiítulos dos trabalhos devem ser escritos de modo que a primeira letra de cada palavra seja maiúscula. (exceto termos como de, por, para, com, como ou for, with, in ...).</li>
									<li style="padding-bottom: 10px;">Seções e subseções devem ser referenciadas com letra maiúscula: Ex: Na Seção 2 é apresentado o modelo do sistema, enquanto na Subseção 3 estão as simulações.</li>
									<li style="padding-bottom: 10px;">As equações devem ser referenciadas pelo número entre parênteses: Ex:  Em (1) é apresentada a probabilidade de erro.</li>
									<li style="padding-bottom: 10px;">As figuras devem ser referenciadas por Fig. seguido do número da figura: Ex:  As probabilidades de erro de bits são apresentadas na Fig.  1.</li>
									<li style="padding-bottom: 10px;">Os títulos dos trabalhos listados nas referências bibliográficas devem ser uniformizados de modo que a primeira letra de cada palavra seja maíscula (exceto termos como em, com, de, para, sem). Ex: Probabilidade de Erro de Bits de Esquemas QAM com Desvanecimento Nakagami</li>
									<li style="padding-bottom: 10px;">Os nomes dos autores citados nas referências devem ser uniformizados de modo que (caso sejam usadas abreviações) apenas os dois primeiros nomes seja abreviados. Ex: K. Sivanesan and N. C. Beaulieu.</li>
									<li style="padding-bottom: 10px;">As referências devem conter todas as informações associadas a cada trabalho. Na primeira ocorrência no texto, as siglas devem aparecer entre parênteses, em letra maiúscula e com fonte romana.</li>
									<li style="padding-bottom: 10px;">Apenas a primeira palavra do elemento textual Palavras-chaves (Index Terms) deve ser escrita em letra maiúscula.</li>
								</ul>
							</p>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
		</div>
		<!-- special models-->


		<div class="agileits-w3layouts-specials" id="datas">
			<h3>DATAS</h3>
			<span></span>
				<div class="special-grids">
					<div class="col-md-6 special-right l-left">
						<div class="l-wid">
							<h4>Datas Importantes</h4>
							<p style="color: white">Cronograma de atividades do ENCOM 2018:</p>
							<p><center><table class="table" height="180" width="580" border="0" bordercolor="#FFF" font="white" style="margin-bottom: 30px">
                   
		                    <tbody><tr>
		                    	<td colspan="2">
		                      <center><font color="white">Atividades ENCOM 2018 / Datas</font></center>
		                      </td>
		                    </tr>
		                      <tr>
		                      <td>&nbsp;&nbsp;<font color="white">Deadline para submissão de artigos:</font></td>
		                      <td><center><font color="white">30/06/2018</font></center></td>
		                    </tr>
		                      <tr>
		                      <td>&nbsp;&nbsp;<font color="white">Resultado da avaliação dos artigos:</font></td>
		                      <td><center><font color="white">30/07/2018</font></center></td>
		                    </tr>
		                      <tr>
		                      <td>&nbsp;&nbsp;<font color="white">Envio da versão final dos artigos aceitos:</font></td>
		                      <td><center><font color="white">30/08/2018</font></center></td>
		                    </tr>
		                      <tr>
		                      <td>&nbsp;&nbsp;<font color="white">Inscrições a partir do dia:</font></td>
		                      <td> <center><font color="white">17/07/2018</center></td>
		                    </tr>
		                 </tbody></table></center></p>
						</div>
						
					</div>
					<div class="col-md-6 special-left l-right l-grids">
						 <figure class="effect-bubba">
								<img src="images/calendar.jpg" alt=""/>
								<figcaption>
									<h4>Datas</h4>
									<p>Não percam as datas relativas ao processo de submissão de trabalhos.</p>																
								</figcaption>			
						 </figure>
					</div>
					<div class="where-spl">
						
						<div class="clearfix"></div>
					</div>
				</div>
			</div>

	<!-- top-brands -->
	<div class="top-brands" id="brands">
		<div class="container">
			<div class="top-brands-agile-head">
			<h3>APOIO E PATROCÍNIO</h3>
			</div>
			<div class="sliderfig brands-agile-grids">
				<ul id="flexiselDemo1">			
					<li>
						<img src="images/brand1.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/brand4.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/brand111.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/brand7.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/brand6.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/IFPE-SERTAO.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/ufba.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/rohdelogo.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/unifacs.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/ifpe.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/ufrb.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/ufpe.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/ufs.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/upe.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/ufpb.jpg" alt=" " class="img-responsive" />
					</li>
					<li>
						<img src="images/ifba.jpg" alt=" " class="img-responsive" />
					</li>
				</ul>
			</div>
			
		</div>
	</div>
	<!-- //top-brands --> 

<!--/contact-->
<div class="contact-main-agileits" id="contact">
		<div class="contact-w3-head">
			<h3>ENTRAR EM CONTATO</h3>
		</div>
		<!--form-stars-here-->
		<div class="w3-agile-contact-grids">
				<div class="left-form-w3-agile">
					<h3>Envie sua mensagem!</h3>
					<form action="#" method="post">
					<div class="upper">
						<div class="form-sub-w3">
							<div class="icon-w3">
								<i class="fa fa-user" aria-hidden="true"></i>
							</div>
								<input type="text" name="Username" placeholder="Usuário" required="" />
						</div>
						<div class="form-sub-w3">
								<div class="icon-w3">
									<i class="fa fa-envelope-o" aria-hidden="true"></i>
								</div>	
									<input type="email" name="Email" placeholder="seu_email@email.com" required="" />
						</div>
						<div class="form-sub-w3">
								<div class="icon-w3">
									<i class="fa fa-comment-o" aria-hidden="true"></i>
								</div>
									<textarea name="Comments" placeholder="Sua mensagem" required=""></textarea>
						</div>
						</div>
						<div class="submit-w3l">
						<input type="submit" value="">
						</div>
					</form>
				</div>
					<!--//form-ends-here-->
					<div class="right-map-w3-agile">
							<h2>Nossa Localização</h2>
							<div class="social-icons-right">
								<h3> Catch on Social</h3>
									<ol>
										<li class="fb"><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
										<li class="twt"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
										<li class="drb"><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
										<li class="ldn"><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
									</ol>
										<ul class="add">
											<li class="dot"> Rua Augusto Viana, s/n - Palácio da Reitoria, Canela, Salvador - CEP: 40110-909</li>
											<li class="mes"> <a href="mailto:encom2018@iecom.org.br">encom2018@iecom.org.br</a></li>
										</ul>
										<div class="clearfix"></div>
							</div>					
							<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3887.5210757470145!2d-38.511163884564446!3d-13.002454963954195!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1spt-BR!2sbr!4v1508992081706" width="600" height="260" frameborder="0" style="border:0" allowfullscreen></iframe>
								<div class="clearfix"></div>				
					</div>
					<div class="clearfix"></div>
		</div>
</div>
<!--/contact-->
	<!-- footer -->
	<div class="footer">
		<div class="container">
			<div class="agile-footer-grids">
			<div class="col-md-4 w3-agile-footer-grid">
					<h3>Newsletter</h3>
					<form action="#" method="post">
						<input type="email" id="mc4wp_email" name="EMAIL" placeholder="Enter your email here" required="">
						<input type="submit" value="Subscribe">
					</form>
				</div>
				<div class="col-md-4 w3-agile-footer-grid">
					<h3>EVENTOS ANTERIORES</h3>
					<ul>
						<li><a target="_blank" href="http://iecom.org.br/encom2017" >Encom 2017</a></li>
						<li><a target="_blank" href="http://iecom.org.br/encom2016" >Encom 2016</a></li>
						<li><a target="_blank" href="http://iecom.org.br/encom2015" >Encom 2015</a></li>
						<li><a target="_blank" href="http://iecom.org.br/encom2014" >Encom 2014</a></li>
						<li><a target="_blank" href="http://iecom.org.br/encom2013" >Encom 2013</a></li>
						<li><a target="_blank" href="http://iecom.org.br/encom2012" >Encom 2012</a></li>
					</ul>
				</div>
				<div class="col-md-4 w3-agile-footer-grid">
					<h3>Redes Sociais:</h3>
					<div class="footer-social-grids">
						<ul>
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-rss"></i></a></li>
						</ul>
					</div>
					<div style="border:0px solid #ccc;padding:10px 0px 3px 0px;text-align:center;background-color:none;min-width:235px; margin: 5px 0 5px 0;">
				</div>
				<div class="clearfix"> </div>
			</div>

		</div>
				<div class="clearfix"> </div>
				<div class="footer-bottom">
				<p>© 2018 Encom . Todos os Direitos Reservados | Design by <a href="http://w3layouts.com">W3layouts</a> and Customized By Encom.</p>
			</div>

</div>
	<!-- //footer -->
	<!-- Default-JavaScript-File -->
	<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="js/bootstrap.min.js"></script>
	
	<!-- Slider-JavaScript -->
	<script src="js/responsiveslides.min.js"></script>
	<script>
		$(function () {
			$("#slider, #slider1").responsiveSlides({
				auto: true,
				nav: true,
				speed: 1500,
				namespace: "callbacks",
				pager: true,
			});
		});
	</script>
<!-- //Slider-JavaScript -->
<!-- //Default-JavaScript-File -->
<script type="text/javascript">
					$(window).load(function() {
						$("#flexiselDemo1").flexisel({
							visibleItems: 4,
							animationSpeed: 1000,
							autoPlay: true,
							autoPlaySpeed: 3000,    		
							pauseOnHover: true,
							enableResponsiveBreakpoints: true,
							responsiveBreakpoints: { 
								portrait: { 
									changePoint:480,
									visibleItems: 1
								}, 
								landscape: { 
									changePoint:640,
									visibleItems:2
								},
								tablet: { 
									changePoint:768,
									visibleItems: 3
								}
							}
						});
						
					});
			</script>
			<script type="text/javascript" src="js/jquery.flexisel.js"></script>
<script src="js/lightGallery.js"></script>
	<script>
    	 $(document).ready(function() {
			$("#lightGallery").lightGallery({
				mode:"fade",
				speed:800,
				caption:true,
				desc:true,
				mobileSrc:true
			});
		});
    </script>

	<!-- start-smoth-scrolling -->
	<script type="text/javascript" src="js/move-top.js"></script>
	<script type="text/javascript" src="js/easing.js"></script>
	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){		
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
			});
		});
	</script>
<!-- start-smoth-scrolling -->
<!-- smooth scrolling -->
	<script type="text/javascript">
		$(document).ready(function() {
		/*
			var defaults = {
			containerID: 'toTop', // fading element id
			containerHoverID: 'toTopHover', // fading element hover id
			scrollSpeed: 1200,
			easingType: 'linear' 
			};
		*/								
		$().UItoTop({ easingType: 'easeOutQuart' });
		});
	</script>
	<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- //smooth scrolling -->

</body>
</html>